# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20170312_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
            preserve_default=False,
        ),
    ]
