# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 22:06
from __future__ import unicode_literals

from django.db import models,migrations
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
    ]
