# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
            preserve_default=False,
        ),
    ]
