# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20170313_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fill_in',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fill_in',
            name='text',
            field=models.TextField(),
        ),
    ]
