# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20170314_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='fill_in',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
