# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20170314_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('lesson_num', models.IntegerField()),
                ('answer', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
        migrations.AlterField(
            model_name='fill_in',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Quiz'),
        ),
    ]
