# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20170314_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fill_in',
            name='answer',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
