# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20170405_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Quiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='fill_in',
            name='question',
        ),
        migrations.DeleteModel(
            name='Fill_in',
        ),
    ]
