# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20170405_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
