# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20170424_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
